basePath: /v1
definitions:
  common.ErrResp:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  common.Image:
    properties:
      cloud_name:
        type: string
      ext:
        type: string
      height:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  model.User:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_verified:
        type: boolean
      password:
        maxLength: 100
        minLength: 6
        type: string
      updated_at:
        type: string
      username:
        maxLength: 100
        minLength: 6
        type: string
    required:
    - email
    - password
    - username
    type: object
  transport.createUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a flashcard learning app API.
  title: Quizen API
  version: "1.0"
paths:
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user and send a verification email
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/transport.createUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrResp'
      summary: Register a new user
      tags:
      - user
swagger: "2.0"
